function pat = assign_coupl_combos(pat)

if strcmp(pat.lead,'Boston Scientific Vercise Directional 2202') || strcmp(pat.lead,'Abbott Infinity Directed (short)')
% coupling combinations (H=Horizontal combination, V=Vertical combination)
    pat.coupl_combos = {'C1X'; 'C2A'; 'C2B'; 'C2C'; 'C3A';...
            'C3B'; 'C3C'; 'C4X';...
            'C2A_C2B'; 'C2B_C2C'; 'C2C_C2A'; 'C3A_C3B'; 'C3B_C3C';...
            'C3C_C3A'; ...
            'C2A_C3A'; 'C2B_C3B'; 'C2C_C3C';...
            'C2A_C2B_C2C'; 'C3A_C3B_C3C';...
            'C1X_C2A';'C1X_C2B';'C1X_C2C';...
            'C4X_C3A';'C4X_C3B';'C4X_C3C';...
            'C2A_C3B';'C2A_C3C';'C2B_C3A';...
            'C2B_C3C';'C2C_C3A';'C2C_C3B'};
elseif strcmp(pat.lead,'Boston Scientific Vercise Standard 2201')
    pat.coupl_combos = {'C1X'; 'C2X'; 'C3X'; 'C4X'; 'C5X';...
                 'C6X'; 'C7X'; 'C8X';...
                 'C1X_C2X'; 'C2X_C3X'; 'C3X_C4X'; 'C4X_C5X'; 'C5X_C6X';...
                 'C6X_C7X'; 'C7X_C8X'};
elseif strcmp(pat.lead,'Medtronic 3887')
    pat.coupl_combos = {'C1X'; 'C2X'; 'C3X'; 'C4X'; ...
                    'C1X_C2X'; 'C2X_C3X'; 'C3X_C4X';...
                     'C1X_C3X'; 'C1X_C4X'; 'C2X_C4X'};
end

end