function [InitialSolution_clean] = load_comsol_solution(pat,Nthreads)
    % loads the initial solutions generated by comsol for each contact
    % configuration in contactNames. Returns a struct with fields
    % corresponding to the configurations. The struct values are 1x8
    % doubles with the electrical field values

    % Input Arguments
    % ---------------
    % path_path :   str, the path to the patient directory
    % hand :    str, left (sin) or right (dx) brain hemisphere
    % unit :    str, the stimulation amplitude of the comsol model

    % Output Arguments
    % ----------------
    % InitialSolution :     struct with fields corresponding to the
    %                       different contact configurations. Each struct 
    %                       consists of 1x8 doubles containing the E-field 
    %                       data:  x,y,z,V,Ex,Ey,Ez,Enorm


    disp('load Comsol solution')

    path = append(pat.path,'EFdistribution_',pat.hand,'_',pat.unit,'/');

    N = length(pat.coupl_combos);
    names = cell(1,N);
    cleaned_values = cell(1,N);
 
    parfor(i=1:N,Nthreads)
        filepath = append(path,'V_EF_cont_',pat.coupl_combos{i,:},'_',pat.hand,'_',pat.unit,'_gnd.csv');
        names{i} = sprintf(pat.coupl_combos{i,:});
        values = readmatrix(filepath,'Delimiter',',','OutputType','double')
        cleaned_values{i} =rmmissing(values);
    end

    InitialSolution_clean = cell2struct(cleaned_values,names,2);

end

